#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char* argv[]) {

	int exit_flag = 0;
	FILE* sfile;

	char name[200];
	char place[100];
	char typeName[100];
	char line[200];
	char* token;
	char* context = NULL;
	size_t size;
	int month =0;
	int day =0;
	int type =0;
	void* list;
	void* ndPtr;
	void* schedInfo;
	int option;
	int cnt;
	
	//Declare Function Pointer1
	void* (*fp) (char* name, char* place, int type, int month, int day);
	fp = sched_genSchedInfo;

	//Declare Function Pointer2
	void* (*fp2)(void* nd);
	fp2 = list_getNextNd;

	//1. FILE pointer open & error handling
	//File open(fopen_s return 0 if file open sucess) if file open failed return 0
	if (fopen_s(&sfile, "schedule.dat", "r") != 0) {
		printf("Schedule File open failed...");
		return 0;
	}
	//if file open failed return 0
	if (sfile == NULL) {
		printf("Schedule File open failed...");
		return 0;
	}

	//initializing the list
	printf("Reading the data files... \n");
	//Generate Linked_list list
	list = (void*)list_genList();



	//2. read from the file
	//One line of file read until the end of file
	while (fgets(line, sizeof(line), sfile) != NULL)
	{
		//the end of file sometimes not null but "\n"
		//add the other condition the end of file
		if (!strcmp(line, "\n")) break;
		//fill code here -- generate genSchedInfo structure by genSchedInfo function
		cnt = 1;
		token = strtok_s(line , " \n", &context);
		while (token != NULL) {
			switch (cnt) {
			case 1: //first token name
				strcpy_s(name, 200, token);
				break;
			case 2: //Secnd token place
				strcpy_s(place, 100, token);
				break;
			case 3: //Third token type
				type = atoi(token);
				break;
			case 4: //4th token month
				month = atoi(token);
				break;
			case 5: //5th token day
				day = atoi(token);
				break;
			default:
				break;
			}
			token = strtok_s(NULL, " \n" , &context);
			cnt++;
		}
		schedInfo = fp(name, place , type, month ,day);


		//put the scheduling info instance generated by genSchedInfo function
		//make new node and add schedInfo		
		list_addTail(schedInfo, list);
	}

	

	//fill code here ---- close the file pointer
	//close file
	if (sfile != NULL) {
		fclose(sfile);
	}

	//print number of schedules
	printf("Read done! %i schedules are read\n", list_len(list));

	//program starts
	while (exit_flag == 0)
	{
		printf("\n\n\n");
		//3. menu printing
		printf("---------------Please Select Menu---------------\n");
		printf("        1 --> All Schedule Print\n");
		printf("        2 --> Specific Month Print\n");
		printf("        3 --> Specific Place Print\n");
		printf("        4 --> Specific Type Print\n");
		printf("                  5 --> Exjt      \n");
		printf("------------------------------------------------\n");


		//4. get option from keyboard
		scanf_s("%d", &option);


		switch (option)
		{
		case 1: //print all the schedules
			printf("printing all the schedules in the scheduler.....\n\n\n");

			ndPtr = list;
			cnt = 0;
			printf("===============List Start===============\n");
			while (list_isEndNode(ndPtr) == 0)
			{
				//file code here -- print count and each scheduling info element
				printf("%d. ", ++cnt);

				ndPtr = list_getNextNd(ndPtr); //get the next node from the list
				schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
				//fill code this part - end
				sched_print(schedInfo);
				printf("\n");
			}
			printf("================List End================\n");

			break;

		case 2:
			//Input certain month
			printf("which month ? : ");
			scanf_s("%i", &month);
			printf("\n");

			ndPtr = list;
			cnt = 0;
			printf("===============List Start===============\n");

			while (list_isEndNode(ndPtr) == 0)
			{
				//file code here -- print scheduling info elements matching to the month

				ndPtr = list_getNextNd(ndPtr); //get the next node from the list
				schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)


				if (sched_getMonth(schedInfo) == month) {
					printf("%d. ", ++cnt);
					sched_print(schedInfo);
					printf("\n");
				}

				//fill code this part - end
			}
			printf("================List End================\n");


			break;

		case 3:
			//Input certain place
			printf("which place ? : ");
			scanf_s("%s", place, 100);
			printf("\n");

			ndPtr = list;
			cnt = 0;
			printf("===============List Start===============\n");

			while (list_isEndNode(ndPtr) == 0)
			{
				//file code here -- print scheduling info elements matching to the place
				

				ndPtr = list_getNextNd(ndPtr); //get the next node from the list
				schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)

				if (!strcmp(place, sched_getPlace(schedInfo))) {
					printf("%d. ", ++cnt);
					sched_print(schedInfo);
					printf("\n");
				}

				//fill code this part - end
			}
			printf("================List End================\n");


			break;

		case 4:
			//Input User Type
			printf("         <which type?>\n");
			sched_printTypes();
			printf("your choice : ");
			scanf_s("%s", typeName , 100);

			int type = sched_convertType(typeName);
			printf("\n\n%d\n\n", type);
			if (type != -1)
			{
				ndPtr = list;
				cnt = 0;
				printf("===============List Start===============\n");
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the place

					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)

					if (sched_getType(schedInfo) == type) {
						printf("%d. ", ++cnt);
						sched_print(schedInfo);
						printf("\n");
					}

					//fill code this part - end
				}
				printf("================List End================\n");

			}
			else
			{
				printf("wrong type name!\n");
			}
			
			break;
		case 5:
			//program end..
			printf("Bye!\n\n");
			exit_flag = 1;
			break;

		default:
			printf("wrong command! input again\n");
			break;
		}


	}


	return 0;
}
